apiVersion: v1
kind: Service
metadata:
  name: x-ray-sample-back-k8s
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: x-ray-sample-back-k8s
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-ray-sample-back-k8s
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: x-ray-sample-back-k8s
      tier: backend
  template:
    metadata:
      labels:
        app: x-ray-sample-back-k8s
        tier: backend
    spec:
      containers:
        - name: x-ray-sample-back-k8s
          image: rnzdocker1/eks-workshop-x-ray-sample-back:e787eff7e3637b9b2bb268281c1556ea38b5c395
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

